config/routes.rb
SharePhoto::Application.routes.draw do
 
 
  resources :albums

  get "album/index"

  get "album/show"

  get "album/new"

  get "album/edit"

  get "album/create"

  get "album/update"

  get "album/destroy"

  get "main/index"

  resources :user_relations
  resources :sessions, only: [:new, :create, :destroy]
  resources :user_prefs
  resources :user_pics
  resources :users

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id, :name, :password, :username, :password_confirmation, :albums_attributes
	has_secure_password

 #before_save { |user| user.username = username.downcase }
	

	has_many :user_pic
	has_many :user_pref
	has_many :user_relation
	has_many :albums

	accepts_nested_attributes_for :albums, :allow_destroy => true

	validates_uniqueness_of :username
	validates_presence_of :password, :on => :create

	validates :name, presence: true, length: {maximum: 30}
	validates :password, presence: true, length: {minimum: 6}
  #	validates :password_confirmation, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @user.albums.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end

  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @user.albums.build
  end


=begin
  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
=end
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      #TheMail.welcome(@user).deliver
      flash[:success] = "Welcome to SharePhoto"
      redirect_to '/albums'
    else
      render 'new'
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
def signed_in_user
    unless signed_in?
      redirect_to signin_path, notice: "Please sign in." 
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
end

app/views/users/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <%= f.fields_for :albums do |album_fields| %>
    <% unless album_fields.object.new_record? %>
      <p> 
        Album: 
        <%=album_fields.text_field :album_name %> 
        <%=album_fields.text_field :album_description %><br />
        <%= link_to 'Edit '+album_fields.object.album_name, edit_album_path(album_fields.object.id) %></td>

      </p>
    <%end%>
  <% end %>

  <%= f.fields_for :albums do |album_fields| %>
    <% if album_fields.object.new_record? %>
      <p>
          Name: <%= album_fields.text_field :album_name %> <br />
          Description: <%= album_fields.text_field :album_description %>
      </p>
    <%end%>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Welcome to SharePhoto</h1>


<h2>Listing users</h2>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Password</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
<%= link_to 'Albums', albums_path %>

app/views/users/new.html.erb
<h1>New user</h1>



<% provide(:title, "Sign Up") %>
<h2>Create New Account</h2>

<div>
  <div>
    <%= form_for(@user) do |f| %>
      <%= render 'error_messages', object: f.object %>

	  <div class="editor-label">
      <%=f.label :name %>
	  </div>
	  <div class="editor-field">
      <%=f.text_field :name, :class => "txtInput" %>
	  </div>

	  <div class="editor-label">
      <%=f.label :username %>
	  </div>
	  <div class="editor-field">
      <%=f.text_field :username, :class => "txtInput" %>
	  </div>

	  <div class="editor-label">
      <%=f.label :password %>
	  </div>
	  <div class="editor-field">
      <%=f.password_field :password, :class => "txtInput" %>
	  </div>

	   <div class="editor-label">
      <%=f.label :password_confirmation, "Password Confirmation" %>
	  </div>
	  <div class="editor-field">
      <%=f.password_field :password_confirmation, :class => "txtInput" %>
	  </div>


	  <br/><br/>

      <%= f.submit "Create Account" %>
	  <br/>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @user.id %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', albums_path %>