config/routes.rb
SharePhoto::Application.routes.draw do
 
 
  resources :albums

  get "album/index"

  get "album/show"

  get "album/new"

  get "album/edit"

  get "album/create"

  get "album/update"

  get "album/destroy"

  get "main/index"

  resources :user_relations
  resources :sessions, only: [:new, :create, :destroy]
  resources :user_prefs
  resources :user_pics
  resources :users

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'sessions#new'

end

app/models/user_pref.rb
class UserPref < ActiveRecord::Base
  attr_accessible :chat, :email, :id

	belongs_to :user 


  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}


end

app/controllers/user_prefs_controller.rb
class UserPrefsController < ApplicationController
  # GET /user_prefs
  # GET /user_prefs.json
  def index
    @user_prefs = UserPref.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_prefs }
    end
  end

  # GET /user_prefs/1
  # GET /user_prefs/1.json
  def show
    @user_pref = UserPref.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_pref }
    end
  end

  # GET /user_prefs/new
  # GET /user_prefs/new.json
  def new
    @user_pref = UserPref.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_pref }
    end
  end

  # GET /user_prefs/1/edit
  def edit
    @user_pref = UserPref.find(params[:id])
  end

  # POST /user_prefs
  # POST /user_prefs.json
  def create
    @user_pref = UserPref.new(params[:user_pref])

    respond_to do |format|
      if @user_pref.save
        format.html { redirect_to @user_pref, notice: 'User pref was successfully created.' }
        format.json { render json: @user_pref, status: :created, location: @user_pref }
      else
        format.html { render action: "new" }
        format.json { render json: @user_pref.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_prefs/1
  # PUT /user_prefs/1.json
  def update
    @user_pref = UserPref.find(params[:id])

    respond_to do |format|
      if @user_pref.update_attributes(params[:user_pref])
        format.html { redirect_to @user_pref, notice: 'User pref was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_pref.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_prefs/1
  # DELETE /user_prefs/1.json
  def destroy
    @user_pref = UserPref.find(params[:id])
    @user_pref.destroy

    respond_to do |format|
      format.html { redirect_to user_prefs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_prefs_helper.rb
module UserPrefsHelper
end

app/views/user_prefs/_form.html.erb
<%= form_for(@user_pref) do |f| %>
  <% if @user_pref.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_pref.errors.count, "error") %> prohibited this user_pref from being saved:</h2>

      <ul>
      <% @user_pref.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :chat %><br />
    <%= f.check_box :chat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_prefs/edit.html.erb
<h1>Editing user_pref</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_pref %> |
<%= link_to 'Back', user_prefs_path %>

app/views/user_prefs/index.html.erb
<h1>Listing user_prefs</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Email</th>
    <th>Chat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_prefs.each do |user_pref| %>
  <tr>
    <td><%= user_pref.id %></td>
    <td><%= user_pref.email %></td>
    <td><%= user_pref.chat %></td>
    <td><%= link_to 'Show', user_pref %></td>
    <td><%= link_to 'Edit', edit_user_pref_path(user_pref) %></td>
    <td><%= link_to 'Destroy', user_pref, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User pref', new_user_pref_path %>

app/views/user_prefs/new.html.erb
<h1>New user_pref</h1>

<%= render 'form' %>

<%= link_to 'Back', user_prefs_path %>

app/views/user_prefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @user_pref.id %>
</p>

<p>
  <b>Email:</b>
  <%= @user_pref.email %>
</p>

<p>
  <b>Chat:</b>
  <%= @user_pref.chat %>
</p>


<%= link_to 'Edit', edit_user_pref_path(@user_pref) %> |
<%= link_to 'Back', user_prefs_path %>