config/routes.rb
SharePhoto::Application.routes.draw do
 
 
  resources :albums

  get "album/index"

  get "album/show"

  get "album/new"

  get "album/edit"

  get "album/create"

  get "album/update"

  get "album/destroy"

  get "main/index"

  resources :user_relations
  resources :sessions, only: [:new, :create, :destroy]
  resources :user_prefs
  resources :user_pics
  resources :users

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'sessions#new'

end

app/models/user_relation.rb
class UserRelation < ActiveRecord::Base
  attr_accessible :enum, :relation_id, :user_id

	belongs_to :user
	 
end

app/controllers/user_relations_controller.rb
class UserRelationsController < ApplicationController
  # GET /user_relations
  # GET /user_relations.json
  def index
    @user_relations = UserRelation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_relations }
    end
  end

  # GET /user_relations/1
  # GET /user_relations/1.json
  def show
    @user_relation = UserRelation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_relation }
    end
  end

  # GET /user_relations/new
  # GET /user_relations/new.json
  def new
    @user_relation = UserRelation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_relation }
    end
  end

  # GET /user_relations/1/edit
  def edit
    @user_relation = UserRelation.find(params[:id])
  end

  # POST /user_relations
  # POST /user_relations.json
  def create
    @user_relation = UserRelation.new(params[:user_relation])

    respond_to do |format|
      if @user_relation.save
        format.html { redirect_to @user_relation, notice: 'User relation was successfully created.' }
        format.json { render json: @user_relation, status: :created, location: @user_relation }
      else
        format.html { render action: "new" }
        format.json { render json: @user_relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_relations/1
  # PUT /user_relations/1.json
  def update
    @user_relation = UserRelation.find(params[:id])

    respond_to do |format|
      if @user_relation.update_attributes(params[:user_relation])
        format.html { redirect_to @user_relation, notice: 'User relation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_relations/1
  # DELETE /user_relations/1.json
  def destroy
    @user_relation = UserRelation.find(params[:id])
    @user_relation.destroy

    respond_to do |format|
      format.html { redirect_to user_relations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_relations_helper.rb
module UserRelationsHelper
end

app/views/user_relations/_form.html.erb
<%= form_for(@user_relation) do |f| %>
  <% if @user_relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_relation.errors.count, "error") %> prohibited this user_relation from being saved:</h2>

      <ul>
      <% @user_relation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :relation_id %><br />
    <%= f.number_field :relation_id %>
  </div>
  <div class="field">
    <%= f.label :enum %><br />
    <%= f.number_field :enum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_relations/edit.html.erb
<h1>Editing user_relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_relation %> |
<%= link_to 'Back', user_relations_path %>

app/views/user_relations/index.html.erb
<h1>Listing user_relations</h1>

<table>
  <tr>
    <th>User</th>
    <th>Relation</th>
    <th>Enum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_relations.each do |user_relation| %>
  <tr>
    <td><%= user_relation.user_id %></td>
    <td><%= user_relation.relation_id %></td>
    <td><%= user_relation.enum %></td>
    <td><%= link_to 'Show', user_relation %></td>
    <td><%= link_to 'Edit', edit_user_relation_path(user_relation) %></td>
    <td><%= link_to 'Destroy', user_relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User relation', new_user_relation_path %>

app/views/user_relations/new.html.erb
<h1>New user_relation</h1>

<%= render 'form' %>

<%= link_to 'Back', user_relations_path %>

app/views/user_relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_relation.user_id %>
</p>

<p>
  <b>Relation:</b>
  <%= @user_relation.relation_id %>
</p>

<p>
  <b>Enum:</b>
  <%= @user_relation.enum %>
</p>


<%= link_to 'Edit', edit_user_relation_path(@user_relation) %> |
<%= link_to 'Back', user_relations_path %>