config/routes.rb
SharePhoto::Application.routes.draw do
 
 
  resources :albums

  get "album/index"

  get "album/show"

  get "album/new"

  get "album/edit"

  get "album/create"

  get "album/update"

  get "album/destroy"

  get "main/index"

  resources :user_relations
  resources :sessions, only: [:new, :create, :destroy]
  resources :user_prefs
  resources :user_pics
  resources :users

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'sessions#new'

end

app/models/user_pic.rb
class UserPic < ActiveRecord::Base
  attr_accessible :caption, :date_modified, :id, :img_path, :tags, :title

	belongs_to :user 
	

end

app/controllers/user_pics_controller.rb
class UserPicsController < ApplicationController
  # GET /user_pics
  # GET /user_pics.json
  def index
    @user_pic = UserPic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_pics }
    end
  end

  # GET /user_pics/1
  # GET /user_pics/1.json
  def show
    @user_pic = UserPic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_pic }
    end
  end

  # GET /user_pics/new
  # GET /user_pics/new.json
  def new
    @user_pic = UserPic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_pic }
    end
  end

  # GET /user_pics/1/edit
  def edit
    @user_pic = UserPic.find(params[:id])
  end

  # POST /user_pics
  # POST /user_pics.json
  def create
    @user_pic = UserPic.new(params[:user_pic])

    respond_to do |format|
      if @user_pic.save
        format.html { redirect_to @user_pic, notice: 'User pic was successfully created.' }
        format.json { render json: @user_pic, status: :created, location: @user_pic }
      else
        format.html { render action: "new" }
        format.json { render json: @user_pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_pics/1
  # PUT /user_pics/1.json
  def update
    @user_pic = UserPic.find(params[:id])

    respond_to do |format|
      if @user_pic.update_attributes(params[:user_pic])
        format.html { redirect_to @user_pic, notice: 'User pic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_pics/1
  # DELETE /user_pics/1.json
  def destroy
    @user_pic = UserPic.find(params[:id])
    @user_pic.destroy

    respond_to do |format|
      format.html { redirect_to user_pics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_pics_helper.rb
module UserPicsHelper
end

app/views/user_pics/_form.html.erb
<%= form_for(@user_pic) do |f| %>
  <% if @user_pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_pic.errors.count, "error") %> prohibited this user_pic from being saved:</h2>

      <ul>
      <% @user_pic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.check_box :tags %>
  </div>
  <div class="field">
    <%= f.label :img-path %><br />
    <%= f.text_field :img-path %>
  </div>
  <div class="field">
    <%= f.label :date-modified %><br />
    <%= f.datetime_select :date-modified %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_pics/edit.html.erb
<h1>Editing user_pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_pic %> |
<%= link_to 'Back', user_pics_path %>

app/views/user_pics/index.html.erb
<h1>Listing user_pics</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Caption</th>
    <th>Tags</th>
    <th>Img-path</th>
    <th>Date-modified</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_pics.each do |user_pic| %>
  <tr>
    <td><%= user_pic.id %></td>
    <td><%= user_pic.title %></td>
    <td><%= user_pic.caption %></td>
    <td><%= user_pic.tags %></td>
    <td><%= user_pic.img-path %></td>
    <td><%= user_pic.date-modified %></td>
    <td><%= link_to 'Show', user_pic %></td>
    <td><%= link_to 'Edit', edit_user_pic_path(user_pic) %></td>
    <td><%= link_to 'Destroy', user_pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User pic', new_user_pic_path %>

app/views/user_pics/new.html.erb
<h1>New user_pic</h1>

<%= render 'form' %>

<%= link_to 'Back', user_pics_path %>

app/views/user_pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @user_pic.id %>
</p>

<p>
  <b>Title:</b>
  <%= @user_pic.title %>
</p>

<p>
  <b>Caption:</b>
  <%= @user_pic.caption %>
</p>

<p>
  <b>Tags:</b>
  <%= @user_pic.tags %>
</p>

<p>
  <b>Img-path:</b>
  <%= @user_pic.img-path %>
</p>

<p>
  <b>Date-modified:</b>
  <%= @user_pic.date-modified %>
</p>


<%= link_to 'Edit', edit_user_pic_path(@user_pic) %> |
<%= link_to 'Back', user_pics_path %>